version: "3"
services:

  app:
    image: miropanak/secmon:v1
    container_name: app
    restart: always
    cap_add:
    - SYS_ADMIN
    volumes:
    - .:/var/www/html/secmon
    - /sys/fs/cgroup/:/sys/fs/cgroup:ro 
    ports:
    - 514:514 
    - 8080:80
    links:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=secmon
    depends_on:
    - db

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=secmon
    volumes:
      - db_data:/var/lib/pgsql/data/
      
volumes:
  db_data: