version: "2.3"
services:
  app:
    build:
      context:  ./
      dockerfile: deployment/dockerfiles/secmon_app.Dockerfile
    container_name: secmon_app
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - .:/var/www/html/secmon
      - /var/log/secmon:/var/log/secmon
    links:
      - db
    environment:
      - POSTGRES_HOST=secmon_db
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=secmon
      - WAIT_HOSTS=secmon_db:5432
    depends_on:
      - db
    networks:
      - app-network

  aggregator:
    build:
      context:  ./
      dockerfile: deployment/dockerfiles/secmon_aggregator.Dockerfile
    container_name: secmon_aggregator
    restart: unless-stopped
    volumes:
      - .:/var/www/html/secmon
      - /var/log/secmon:/var/log/secmon
    depends_on:
      - app
    networks:
      - app-network

  normalizer:
    build:
      context:  ./
      dockerfile: deployment/dockerfiles/secmon_normalizer.Dockerfile
    container_name: secmon_normalizer
    restart: unless-stopped
    expose: 
      - 5557
    volumes:
      - .:/var/www/html/secmon
      - /var/log/secmon:/var/log/secmon
    depends_on:
      - app
    networks:
      - app-network

  db_retention:
    build:
      context:  ./
      dockerfile: deployment/dockerfiles/secmon_db_retention.Dockerfile
    container_name: secmon_db_retention
    restart: unless-stopped
    volumes:
      - .:/home/secmon
    environment:
    - WAIT_HOSTS=secmon_db:5432
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: postgres
    container_name: secmon_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=secmon
    volumes:
      - db_data:/var/lib/pgsql/data/
    networks:
      - app-network
    
volumes:
  db_data:

#Docker Networks
networks:
  app-network:
    driver: bridge